### ISSUE TITLE
website: figure out how to properly generate static HTML from Hugo

### ISSUE THREAD

**Issue by odeke-em** [google/sqlcommenter#10]
We need to figure out how to properly generate HTML from the website itself that'll then be rendered properly by the content retrieved from the gh-pages here.

@smg727 you have access to the sqlcommenter-website that I created and it can be run locally
by
```shell
hugo serve
```
or to generate HTML that'll be found in the /public directory
```shell
hugo
```

**Comment by odeke-em** [comment]
After publishing here, the website will then be accessible at https://google.github.io/sqlcommenter/
but currently looks wonky until this issue is resolved.

**Comment by odeke-em** [comment]
Kindly pinging you @smg727 to help out here as I currently don't have bandwidth.

**Comment by balachandr** [comment]
@odeke-em , can you point me to the website source you created.

**Comment by odeke-em** [comment]
@balachandr the website source is https://github.com/orijtech/sqlcommenter-website and one can generate the public HTML just by
```shell
hugo
```
and then run the website by
```shell
hugo serve
```
and then visiting http://localhost:1313/

**Comment by odeke-em** [comment]
Completed, thanks to @smg727’s help.
