### ISSUE TITLE
Traces not showing with Go Implementation in Query Insights

### ISSUE THREAD

**Issue by kostyay** [google/sqlcommenter#211]
Hey
I've implemented this in my code.
I can see that `traceparent` is added to each query, unfortunately though the traces are not being linked up to my application traces. The query insights "end to end" view only shows the query breakdown without any of the application traces.
Perhaps `tracespan` is missing?
Any ideas how to debug this?

**Comment by sjs994** [comment]
Hi @kostyay,

`traceparent` contains the trace-id and parent span-id, which is what is needed to link the query plans with application traces.

Now, to debug we can take a look at few things:
1. Can you check in your application layer what is the trace-id(part of traceparent) and is it same as the trace-id populated as part of query ?
2. Is the application exporting traces to GCP by using OpenTelemetry library ?

**Comment by kostyay** [comment]
Hey
Thanks for the reply.
Yes the traceids match and the application is reporting the traces using opentelemetry and they show in the Trace view of the console.
However Query Insights traces don't link up with the application traces

**Comment by kostyay** [comment]
Postgres 14

**Comment by kostyay** [comment]
Just as a reference it doesn't work with Postgres 11 too. 
We have a support ticket with Google about this, if you want some links/trace ids I can email them to you

**Comment by sjs994** [comment]
@kostyay 
> I can see that `traceparent` is added to each query

Can you please give more information on how you checked that `traceparent` is populated for each query i.e. 
1. By using application logs or database logs ? OR
2. traces from Query Insights UI ?

**Comment by kostyay** [comment]
1. I enabled debug logging in pgx driver that forces it to print all the queries before its running and saw /*traceparent=xxx*/ on the queries
2. I also saw them in the postgres.log file in the CloudSQL instance.
