### ISSUE TITLE
Docs Update : Add details for Spring Hibernate applications using application.yml

### ISSUE THREAD

**Issue by shubhwip** [google/sqlcommenter#224]
There are applications using spring hibernate which don't use persistence.xml and also don't manage EntityManager using @Configuration.
Some applications define their spring hibernate properties in application.yml.
There should be documentation to help those users.

I can submit a PR :)

**Comment by sjs994** [comment]
Hi Shubham,

Thanks for bringing this to attention. 
Please feel free to open a PR.
