### ISSUE TITLE
Pin opentelemetry-api ~= 1.0

### ISSUE THREAD

**Issue by aabmass** [google/sqlcommenter#68]
Opentelemetry has released a stable 1.0 so I recommend adding a version specifier `~= 1.0`. There may be some small breaking changes since then to resolve.

https://github.com/google/sqlcommenter/blob/53f07a3efaa8ad3b56281262b16818e89c9e4b6e/python/sqlcommenter-python/setup.py#L43

**Comment by ymotongpoo** [comment]
I didn't realize this issue but I think this is fixed in #73. 

@omirho Could you triage this?

**Comment by aabmass** [comment]
I can close it @ymotongpoo :)
